config/routes.rb
Rails.application.routes.draw do

  get 'signups/new'
  get 'signups/quotation'
  get 'inquiry/new'

  root "meocheki_calc#index"

  get 'admin/index',to: 'admin#index'
  get 'rental_plans',to: 'rental_plans#index'
  get 'meo' ,to: 'meo_calc#index'
  get 'hosikakutokun',to: 'hosikakutokun_calc#index'
  get 'thanks',to: 'meocheki_calc#thanks_page'
  get 'multiple_stores', to: 'multiple_stores#index'
  
  post 'download_meocheki',to: 'download_pdf#meocheki_quotation'
  post 'download_rental',to: 'download_pdf#rental_quotation'
  post 'download_meo',to: 'download_pdf#meo_quotation'
  post 'download_hoshikakutokun',to: 'download_pdf#hoshikakutokun_quotation'

  post 'download_pdf/generate_quotation'

  resources :plans do
  end
  
  resources :inquiries 
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :signups
  post  'signups/confirm' => 'signups#confirm'   # 確認画面
  post  'signups/confirm2' => 'signups#confirm2'   # 確認画面
  post  'signups/thanks'  => 'signups#thanks'    # 送信完了画面
  post  'signups/thanks2'  => 'signups#thanks2'    # 送信完了画面


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/signup.rb
class Signup
	include ActiveModel::Model
	include ActiveModel::Attributes
    attr_accessor :company_name, :department, :name, :email, 
	:phone_number, :normal, :oem, :content

	attribute :company_name,  	:string, default: ''
	attribute :name,			:string, default: ''
	attribute :department, 		:string, default: ''
	attribute :email, 			:string, default: ''
	attribute :phone_number, 	:integer, default: ''
	attribute :content,			:integer, default: ''

    validates :company_name, :presence => {:message => '会社名の入力をお願いいたします'}
    validates :name, :presence => {:message => 'お名前の入力をお願いいたします'}
    validates :department, :presence => {:message => '部署名の入力をお願いいたします'}
    validates :email, :presence => {:message => 'Eメールアドレスの入力をお願いいたします'}
    validates :phone_number, :presence => {:message => 'お電話番号の入力をお願いいたします'}

	private

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @signup = Signup.new
    @service = params[:service]
    @plan = params[:plan]
    @feature = params[:feature]
    @number_of_business = params[:number_of_business]
    @keywords = params[:keywords]

    render :action => 'new'
  end
  
  def confirm
    # 入力値のチェック
    @signup = Signup.new(params[:signup].permit(:company_name, :department,
      :name, :email, :phone_number, :content))
    @service = params[:service]
    @plan = params[:plan]
    @number_of_business = params[:number_of_business]
    @keywords = params[:keywords]
    @feature = params[:feature]

      if @signup.valid?
        # OK。確認画面を表示
        render :action => 'confirm'
      else
        # NG。入力画面を再表示
      render :action => 'new'
    end
  end

  def quotation
    @signup = Signup.new
    @service = params[:service]
    @plan = params[:plan]
    @feature = params[:feature]
    @init_support_options = params[:init_support_options]
    @number_of_business = params[:number_of_business]
    @keywords = params[:keywords]
    @init_price = params[:init_price]
    @price_for_options = params[:price_for_options]
    @first_month_price = params[:first_month_price]
    @monthly_price = params[:monthly_price]
    @price_for_bulk_management = params[:price_for_bulk_management]
    @price_for_meo = params[:price_for_meo]
    @price_for_meo_analysis = params[:price_for_meo_analysis]
    @price_for_sns_package = params[:price_for_sns_package]
    @price_for_advanced_ranking_information = params[:price_for_advanced_ranking_information]
    @price_for_review_package = params[:price_for_review_package]
    @price_for_support = params[:price_for_support]
    @price_for_initial_registration = params[:price_for_initial_registration]
    
    @plan_price = params[:plan_price]
    @price_for_post = params[:price_for_post]
    @price_for_report = params[:price_for_report]
    @price_for_review_management = params[:price_for_review_management]
    @price_for_bulk_edit = params[:price_for_bulk_edit]
    @price_for_analysis = params[:price_for_analysis]
    @price_for_license = params[:price_for_license]
    @price_for_bulk_registration = params[:price_for_bulk_registration]

    render :action => 'quotation'
  end

  def confirm2
    # 入力値のチェック
    @signup = Signup.new(params[:signup].permit(:company_name, :department,
      :name, :email, :phone_number, :content))
    @service = params[:service]
    @plan = params[:plan]
    @number_of_business = params[:number_of_business]
    @keywords = params[:keywords]
    @feature = params[:feature]
    @init_support_options = params[:init_support_options]
    @init_price = params[:init_price]
    @price_for_options = params[:price_for_options]
    @first_month_price = params[:first_month_price]
    @monthly_price = params[:monthly_price]
    @plan_price = params[:plan_price]
    @price_for_bulk_management = params[:price_for_bulk_management]
    @price_for_meo = params[:price_for_meo]
    @price_for_meo_analysis = params[:price_for_meo_analysis]
    @price_for_sns_package = params[:price_for_sns_package]
    @price_for_advanced_ranking_information = params[:price_for_advanced_ranking_information]
    @price_for_review_package = params[:price_for_review_package]
    @price_for_support = params[:price_for_support]
    @price_for_initial_registration = params[:price_for_initial_registration]
    @price_for_post = params[:price_for_post]
    @price_for_report = params[:price_for_report]
    @price_for_review_management = params[:price_for_review_management]
    @price_for_bulk_edit = params[:price_for_bulk_edit]
    @price_for_analysis = params[:price_for_analysis]
    @price_for_license = params[:price_for_license]
    @price_for_bulk_registration = params[:price_for_bulk_registration]
    
      if @signup.valid?
        # OK。確認画面を表示
        render :action => 'confirm2'
      else
        # NG。入力画面を再表示
      render :action => 'quotation'
    end
  end

  def thanks
    # メール送信
    @signup = Signup.new(params[:signup].permit(:company_name, :department,
      :name, :email, :phone_number, :content))   
    @service = params[:service]
    @plan = params[:plan]
    @number_of_business = params[:number_of_business]
    @keywords = params[:keywords]
    @feature = params[:feature]
    
    SignupMailer.signup_email(@signup, @service, @plan, @number_of_business, @keywords, @feature).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/confirm.html.erb
<div class="page-title-lv1 col-md-12">
	<span>
	<h1 style="margin-left:8rem;">お申し込み内容のご確認</h1>
  <p style="margin-left:8rem;">・以下の内容で申し込みフォームを送信します</p>
  <p style="margin-left:8rem;">・弊社担当者から、お申し込み内容についてお電話もしくはメールにて連絡させていただきます</p>
	</span>
</div>
<div class="" style="background-color: #F5F7F8;">
	<div class="container inquiry-form">
	    <div class="row">
			<div class="col-md-12 inquiry-box" >
<%= form_for @signup, :url => signups_thanks_path do |f| %>
  <table class="table">
  <tr>
    <th>お申し込みになるサービス</th>
    <%= hidden_field_tag :service, @service %>
		<td style="text-align: left;"><%= @service %></td>
	</tr>
  <% if @plan.present? %>
	<tr>
    <th>お申し込みになるプラン</th>
    <%= hidden_field_tag :plan, @plan %>
    <td style="text-align: left;"> <%= @plan %></td>
  </tr>
  <% end %>
  <% if @number_of_business.present? %>
	<tr>
    <th>お申し込みの店舗数</th>
    <%= hidden_field_tag :number_of_business, @number_of_business %>
    <td style="text-align: left;"> <%= @number_of_business %></td>
  </tr>
  <% end %>
  <% if @keywords.present? %>
	<tr>
    <th>お申し込みになるキーワード数（順位取得用）</th>
    <%= hidden_field_tag :keywords, @keywords %>
    <td style="text-align: left;"> <%= @keywords %></td>
  </tr>
  <% end %>
  <% if @feature.present? %>
	<tr>
    <th>お申し込みの機能</th>
    <%= hidden_field_tag :feature, @feature %>
    <td style="text-align: left; list-style: none"> <%= @feature.html_safe %></td>
  </tr>
  <% end %>

    <tr>
      <th>会社名</th>
      <td style="text-align: left;">
      <%= f.hidden_field :company_name %>
        <%= @signup.company_name %>
      </td>
    </tr>
    <tr>
      <th>部署名</th>
      <td style="text-align: left;">
        <%= f.hidden_field :department %>
        <%= @signup.department %>
      </td>
    </tr>
    <tr>
      <th>ご担当者様のお名前</th>
      <td style="text-align: left;">
        <%= f.hidden_field :name %>
        <%= simple_format(@signup.name) %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td style="text-align: left;">
        <%= f.hidden_field :email %>
        <%= simple_format(@signup.email) %>
      </td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td style="text-align: left;">
        <%= f.hidden_field :phone_number %>
        <%= simple_format(@signup.phone_number) %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td style="text-align: left;">
        <%= f.hidden_field :content %>
        <%= simple_format(@signup.content) %>
      </td>
    </tr>
  </table>
	<div class="center">
  <%= f.submit '送信', :class => 'btn btn-primary' %>
	</div>
<% end %>

  </div>
	</div>
</div>
</div>

app/views/signups/confirm2.html.erb
<div class="page-title-lv1 col-md-12">
  <span>
    <h1 style="margin-left:8rem;">お見積り内容のご確認</h1>
    <p style="margin-left:8rem;">・以下の内容でお見積り書を作成いたします</p>
    <p style="margin-left:8rem;"></p>
  </span>
</div>
<div class="" style="background-color: #F5F7F8;">
  <div class="container inquiry-form">
    <div class="row">
      <div class="col-md-12 inquiry-box">
        <%= form_for @signup, url: {controller: 'download_pdf', action: 'generate_quotation' } do |f| %>
        <table class="table">
          <tr>
            <th>サービス名</th>
            <%= hidden_field_tag :service, @service %>
            <td style="text-align: left;"><%= @service %></td>
          </tr>
          <% if @plan.present? %>
          <tr>
            <th>プラン名</th>
            <%= hidden_field_tag :plan, @plan %>
            <td style="text-align: left;"> <%= @plan %></td>
          </tr>
          <% end %>
          <% if @number_of_business.present? %>
          <tr>
            <th>店舗数</th>
            <%= hidden_field_tag :number_of_business, @number_of_business %>
            <td style="text-align: left;"> <%= @number_of_business %></td>
          </tr>
          <% end %>
          <% if @keywords.present? %>
          <tr>
            <th>キーワード数（順位取得用）</th>
            <%= hidden_field_tag :keywords, @keywords %>
            <td style="text-align: left;"> <%= @keywords %></td>
          </tr>
          <% end %>
          <% if @init_support_options.present? %>
          <tr>
            <th>導入サポート</th>
            <%= hidden_field_tag :init_support_options, @init_support_options %>
            <td style="text-align: left; list-style: none"> <%= @init_support_options.html_safe %></td>
          </tr>
          <% end %>
          <% if @feature.present? %>
          <tr>
            <th>選択された機能</th>
            <%= hidden_field_tag :feature, @feature %>
            <td style="text-align: left; list-style: none"> <%= @feature.html_safe %></td>
          </tr>
          <% end %>

          <tr>
            <th>会社名</th>
            <td style="text-align: left;">
              <%= f.hidden_field :company_name %>
              <%= @signup.company_name %>
            </td>
          </tr>
          <tr>
            <th>部署名</th>
            <td style="text-align: left;">
              <%= f.hidden_field :department %>
              <%= @signup.department %>
            </td>
          </tr>
          <tr>
            <th>ご担当者様のお名前</th>
            <td style="text-align: left;">
              <%= f.hidden_field :name %>
              <%= @signup.name %>
            </td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td style="text-align: left;">
              <%= f.hidden_field :email %>
              <%= @signup.email %>
            </td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td style="text-align: left;">
              <%= f.hidden_field :phone_number %>
              <%= @signup.phone_number %>
            </td>
          </tr>
        </table>

        <%= hidden_field_tag :service, @service %>
        <%= hidden_field_tag :plan, @plan %>
        <%= hidden_field_tag :number_of_business, @number_of_business %>
        <%= hidden_field_tag :keywords, @keywords %>
        <%= hidden_field_tag :feature, @feature %>
        <%= hidden_field_tag :init_support_options, @init_support_options %>
        <%= hidden_field_tag :init_price, @init_price %>
        <%= hidden_field_tag :price_for_options, @price_for_options %>
        <%= hidden_field_tag :first_month_price, @first_month_price %>
        <%= hidden_field_tag :monthly_price, @monthly_price %>
        <%= hidden_field_tag :plan_price, @plan_price %>
        <%= hidden_field_tag :price_for_bulk_management, @price_for_bulk_management %>
        <%= hidden_field_tag :price_for_meo, @price_for_meo %>
        <%= hidden_field_tag :price_for_meo_analysis, @price_for_meo_analysis %>
        <%= hidden_field_tag :price_for_sns_package, @price_for_sns_package %>
        <%= hidden_field_tag :price_for_advanced_ranking_information,  @price_for_advanced_ranking_information %>
        <%= hidden_field_tag :price_for_review_package, @price_for_review_package %>
        <%= hidden_field_tag :price_for_support, @price_for_support %>
        <%= hidden_field_tag :price_for_initial_registration, @price_for_initial_registration %>

        <%= hidden_field_tag :price_for_post, @price_for_post %>
        <%= hidden_field_tag :price_for_report, @price_for_report %>
        <%= hidden_field_tag :price_for_review_management, @price_for_review_management %>
        <%= hidden_field_tag :price_for_bulk_edit, @price_for_bulk_edit %>
        <%= hidden_field_tag :price_for_analysis, @price_for_analysis %>
        <%= hidden_field_tag :price_for_license, @price_for_license%>
        <%= hidden_field_tag :price_for_bulk_registration, @price_for_bulk_registration %>
        <div class="center">
          <%= f.submit '送信', :class => 'btn btn-primary mt-2' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/signups/new.html.erb
<div class="page-title-lv1 col-md-12">
	<span>
	<h1 style="margin-left:8rem;">サービス利用のお申し込み</h1>
  <p style="margin-left:8rem;"></p>
  <p style="margin-left:8rem;">お申し込みになりたいサービス・プランがお決まりの場合は、フォームに必要事項を入力の上で送信ください<br>
弊社担当からお申し込み内容について、お電話もしくはメールにて連絡させていただきます</p>
	</span>
</div>
<div class=""  style="background-color: #F5F7F8;">
	<div class="container inquiry-form">
	    <div class="row">
			<div class="col-md-12 inquiry-box" >
            <div class="お申し込みのサービス">
                <label for="">お申し込みになるサービス</label>
                <h4 class="page-title-lv2 "><%= @service %></h4>
                <% if @plan %>
                    <label for="">お申し込みになるプラン</label>
                    <h4 class="page-title-lv2 "><%= @plan %></h4>
                <% end %>
                <% if @number_of_business %>
                    <label for="">お申し込みの店舗数</label>
                    <h4 class="page-title-lv2"><%= @number_of_business %></h4>
                    <small class="ml-3">*お申し込みの店舗数は、ご契約の際にご変更いただけます</small>
                <% end %>
                <% if @keywords %>
                    <label for="">お申し込みになるキーワード数（順位取得用）</label>
                    <h4 class="page-title-lv2"><%= @keywords %></h4>
                    <small class="ml-3">*お申し込みのキーワード数は、ご契約の際にご変更いただけます</small>
                <% end %>
                <% if @feature %>
                    <label for="">お申し込みの機能</label>
                    <h4 class="page-title-lv2" style="list-style: none"><%= @feature.html_safe %></h4>
                <% end %>

            </div>
                <div class="box">
                    <div class="">
                    <% if @signup.errors.any? %>
                    <div class="alert alert-danger" role="alert">
                    <strong>入力内容にエラーがあります!</strong>
                    <ul>
                        <% @signup.errors.each do |attr, msg| %>
                        <li><%= '◆ '+ msg %></li>
                        <% end %>
                    </ul>
                    </div>
                    <% end %>

        <%= form_for @signup, :url => signups_confirm_path do |f| %>
            <%= f.label :会社名 %>
            <%= f.text_field :company_name, :placeholder => "会社名を入力してください" %>
            <%= f.label :部署名 %>
            <%= f.text_field :department, :placeholder => "部署名を入力してください"  %>
            <%= f.label :ご担当者様 %>
            <%= f.text_field :name, :placeholder => "お名前を入力してください"  %>
            <%= f.label :メールアドレス %>
            <%= f.text_field :email, :placeholder => "メールアドレスを入力してください"  %>
            <%= f.label :電話番号 %>
            <%= f.text_field :phone_number, :placeholder => "電話番号を入力してください"  %>
            <%= f.label :その他・相談したいこと %><br>
            <%= f.text_area :content, :placeholder => "担当者に伝えておきたいこと等がありましたら、ぜひご記載をお願いいたします"  %><br>
            <%= hidden_field_tag :service, @service %>
            <%= hidden_field_tag :plan, @plan %>
            <%= hidden_field_tag :number_of_business, @number_of_business %>
            <%= hidden_field_tag :keywords, @keywords %>
            <%= hidden_field_tag :feature, @feature %>

            <div class="center" >
            <%= f.submit :送信する, class: 'btn btn-lg btn-primary' %><br>
            </div>
            <% end %>
                <br>
                </div>	
            </div>
        </div>
        </div>
    </div>
	</div>
</div>
</div>

app/views/signups/quotation.html.erb
<div class="page-title-lv1 col-md-12">
	<span>
		<h1 style="margin-left:8rem;">お見積もり内容のご確認</h1>
		<p style="margin-left:8rem;">以下の内容でお見積り書を作成します</p>
		<p style="margin-left:8rem;"></p>
	</span>
</div>
<div class="" style="background-color: #F5F7F8;">
	<div class="container inquiry-form">
		<div class="row">
			<div class="col-md-12 inquiry-box">
				<div class="お申し込みのサービス">
					<label for="">お見積りさせていただくサービス</label>
					<h4 class="page-title-lv2 "><%= @service %></h4>
					<% if @plan %>
					<label for="">お見積りさせていただくプラン</label>
					<h4 class="page-title-lv2 "><%= @plan %></h4>
					<% end %>
					<% if @number_of_business %>
					<label for="">店舗数</label>
					<h4 class="page-title-lv2"><%= @number_of_business %></h4>
					<small class="ml-3">*お申し込みの店舗数は、ご契約の際にご変更いただけます</small>
					<% end %>
					<% if @keywords %>
					<label for="">キーワード数（順位取得用）</label>
					<h4 class="page-title-lv2"><%= @keywords %></h4>
					<small class="ml-3">*お申し込みのキーワード数は、ご契約の際にご変更いただけます</small>
					<% end %>
					<% if @init_support_options %>
					<label for="">選択された導入サポート</label>
					<h4 class="page-title-lv2" style="list-style: none"><%= @init_support_options.html_safe %></h4>
					<% end %>
					<% if @feature %>
					<label for="">選択されたオプション機能</label>
					<h4 class="page-title-lv2" style="list-style: none"><%= @feature.html_safe %></h4>
					<% end %>

				</div>
				<div class="box">
					<div class="">
						<% if @signup.errors.any? %>
						<div class="alert alert-danger" role="alert">
							<strong>入力内容にエラーがあります!</strong>
							<ul>
								<% @signup.errors.each do |attr, msg| %>
								<li><%= '◆ '+ msg %></li>
								<% end %>
							</ul>
						</div>
						<% end %>

						<%= form_for @signup, :url => signups_confirm2_path do |f| %>
						<%= f.label :会社名 %>
						<%= f.text_field :company_name, :placeholder => "会社名を入力してください" %>
						<%= f.label :部署名 %>
						<%= f.text_field :department, :placeholder => "部署名を入力してください"  %>
						<%= f.label :ご担当者様 %>
						<%= f.text_field :name, :placeholder => "お名前を入力してください"  %>
						<%= f.label :メールアドレス %>
						<%= f.text_field :email, :placeholder => "メールアドレスを入力してください"  %>
						<%= f.label :電話番号 %>
						<%= f.text_field :phone_number, :placeholder => "電話番号を入力してください"  %>
						<%= hidden_field_tag :service, @service %>
						<%= hidden_field_tag :plan, @plan %>
						<%= hidden_field_tag :number_of_business, @number_of_business %>
						<%= hidden_field_tag :keywords, @keywords %>
						<%= hidden_field_tag :feature, @feature %>
						<%= hidden_field_tag :init_support_options, @init_support_options %>
						<%= hidden_field_tag :init_price, @init_price %>
						<%= hidden_field_tag :price_for_options, @price_for_options %>
						<%= hidden_field_tag :first_month_price, @first_month_price %>
						<%= hidden_field_tag :monthly_price, @monthly_price %>
						<%= hidden_field_tag :plan_price, @plan_price %>

						<%= hidden_field_tag :price_for_bulk_management, @price_for_bulk_management %>
						<%= hidden_field_tag :price_for_meo, @price_for_meo %>
						<%= hidden_field_tag :price_for_meo_analysis, @price_for_meo_analysis %>
						<%= hidden_field_tag :price_for_sns_package, @price_for_sns_package %>
						<%= hidden_field_tag :price_for_advanced_ranking_information,  @price_for_advanced_ranking_information %>
						<%= hidden_field_tag :price_for_review_package, @price_for_review_package %>
						<%= hidden_field_tag :price_for_support, @price_for_support %>
						<%= hidden_field_tag :price_for_initial_registration, @price_for_initial_registration %>

						<%= hidden_field_tag :price_for_post, @price_for_post %>
						<%= hidden_field_tag :price_for_report, @price_for_report %>
						<%= hidden_field_tag :price_for_review_management, @price_for_review_management %>
						<%= hidden_field_tag :price_for_bulk_edit, @price_for_bulk_edit %>
						<%= hidden_field_tag :price_for_analysis, @price_for_analysis %>
						<%= hidden_field_tag :price_for_license, @price_for_license%>
						<%= hidden_field_tag :price_for_bulk_registration, @price_for_bulk_registration %>
						<div class="center">
							<%= f.submit :送信する, class: 'btn btn-lg btn-primary mt-5' %><br>
						</div>
						<% end %>
						<br>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>

app/views/signups/thanks.html.erb
<div class="page-header">
  <h1>お申し込みが完了いたしました</h1>
</div>
<p>
  お申し込みありがとうございます。
  弊社担当者より数日以内にご連絡させていただきます
</p>

app/views/signups/thanks.thml.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>