config/routes.rb
Rails.application.routes.draw do

  get 'signups/new'
  get 'signups/quotation'
  get 'inquiry/new'

  root "meocheki_calc#index"

  get 'admin/index',to: 'admin#index'
  get 'rental_plans',to: 'rental_plans#index'
  get 'meo' ,to: 'meo_calc#index'
  get 'hosikakutokun',to: 'hosikakutokun_calc#index'
  get 'thanks',to: 'meocheki_calc#thanks_page'
  get 'multiple_stores', to: 'multiple_stores#index'
  
  post 'download_meocheki',to: 'download_pdf#meocheki_quotation'
  post 'download_rental',to: 'download_pdf#rental_quotation'
  post 'download_meo',to: 'download_pdf#meo_quotation'
  post 'download_hoshikakutokun',to: 'download_pdf#hoshikakutokun_quotation'

  post 'download_pdf/generate_quotation'

  resources :plans do
  end
  
  resources :inquiries 
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :signups
  post  'signups/confirm' => 'signups#confirm'   # 確認画面
  post  'signups/confirm2' => 'signups#confirm2'   # 確認画面
  post  'signups/thanks'  => 'signups#thanks'    # 送信完了画面
  post  'signups/thanks2'  => 'signups#thanks2'    # 送信完了画面


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_how-to-sign-up.html.erb
<div class="col-md-12">
	<section class="section-container-lv1">
		<header class="title-container">
		<h1 class="title-lv1">ご利用開始までの流れ</h1>
		</header>

		<section class="section-lv1">
		<div class="box-text-01">
			<h2 class="title-lv2">お申し込み・問い合わせ</h2>
		</div>
		<div class="panel-col row">
			<div class="panel-col-left col-md-6" style="background: skyblue">
			<%= image_tag 'WEBページのアイコン.png', class:'icon' %>
			<%= image_tag 'ノートPCアイコン.png', class:'icon' %>
			</div>
			<div class="panel-col-right col-md-6" style="background: pink">
			<ul class="list-lv1">
			<li class="list-lv1-itme">
			・こちらのフォームよりお気軽にお問い合わせください
			</li>
			<li class="list-lv1-itme">
			・必要事項を入力し「送信ボタン」を押すだけで完了です
			</li>
			</ul>
			<br>
			</div>
		</div>
		</section>

		<section class="section-lv1">
		<div class="box-text-01">
			<h2 class="title-lv2">担当営業から連絡・打ち合わせ</h2>
		</div>
		<div class="panel-col row">
			<div class="panel-col-left col-md-6" style="background: skyblue">
			<%= image_tag 'サラリーマン.png', class:'icon' %>
			<%= image_tag '電話発信中のフリーアイコン.png', class:'icon' %>
			</div>
			<div class="panel-col-right col-md-6" style="background: pink">
			<ul class="list-lv1">
			<li class="list-lv1-itme">
			・お問い合わせいただいてから２日以内に、弊社担当者からお電話orEメールにてご連絡させていただきます。
			</li>
			<li class="list-lv1-itme">
			・オンライン・オフラインで打ち合わせを実施させていただき、
			お客様のご質問や現状の課題等についてお話を伺いながら、最適なツール・プランの組み合わせをご提案させていただきます。
			</li>
			</ul>
			<br>
			</div>
		</div>
		</section>

		<section class="section-lv1">
		<div class="box-text-01">
			<h2 class="title-lv2">ご契約・アカウント発行</h2>
		</div>
		<div class="panel-col row">
			<div class="panel-col-left col-md-6" style="background: skyblue">
			<%= image_tag 'サラリーマン.png', class:'icon' %>
			<%= image_tag '電話発信中のフリーアイコン.png', class:'icon' %>
			</div>
			<div class="panel-col-right col-md-6" style="background: pink">
			<ul class="list-lv1">
			<li class="list-lv1-itme">
			・お問い合わせいただいてから２日以内に、弊社担当者からお電話orEメールにてご連絡させていただきます。
			</li>
			<li class="list-lv1-itme">
			・オンライン・オフラインで打ち合わせを実施させていただき、
			お客様のご質問や現状の課題等についてお話を伺いながら、最適なツール・プランの組み合わせをご提案させていただきます。
			</li>
			</ul>
			<br>
			</div>
		</div>
		</section>

			<section class="section-lv1">
		<div class="box-text-01">
			<h2 class="title-lv2">ご利用開始</h2>
		</div>
		<div class="panel-col row">
			<div class="panel-col-left col-md-6" style="background: skyblue">
			<%= image_tag 'サラリーマン.png', class:'icon' %>
			<%= image_tag '電話発信中のフリーアイコン.png', class:'icon' %>
			</div>
			<div class="panel-col-right col-md-6" style="background: pink">
			<ul class="list-lv1">
			<li class="list-lv1-itme">
			・お問い合わせいただいてから２日以内に、弊社担当者からお電話orEメールにてご連絡させていただきます。
			</li>
			<li class="list-lv1-itme">
			・オンライン・オフラインで打ち合わせを実施させていただき、
			お客様のご質問や現状の課題等についてお話を伺いながら、最適なツール・プランの組み合わせをご提案させていただきます。
			</li>
			</ul>
			<br>
		</div>
		</section>
	</section>
</div>

app/views/shared/_notification.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : (key == 'alert' ? 'danger' : key) %> pull-right">
      <%= raw value unless value.blank? %>
    </div>
  <% end %>
  <% flash.clear if flash.present? %>
</div>

app/views/shared/_page-title-lv1.html.erb
<div class="page-title-lv1 col-md-12">
	<span>
	<p>最適なおすすめプランがすぐわかる♪</p>
	<h1>料金シミュレーション</h1>
	</span>
</div>

app/views/shared/_submit_form.html.erb
<div class="row m-4"></div>
<div class="container">
    <div class="border shadow row" style="padding: 1em;">
        <div class="col-7">
            <h5>申し込みフォーム</h5>
        </div>
        <div class="col-5"> </div>
            <div class="col-5">
                <%= text_field_tag :business_name, "", {class: "form-control", style: "margin-bottom:1em;", placeholder: "御社名をご記入ください",required: true}  %>
                <%= email_field_tag :email, "", {class: "form-control",placeholder: "メールアドレスをご記入ください",required: true}  %>
            </div>
            <div id="select-payment-type" class="col-md-2">
                <div class="row">
                    <%= label :payment_type, '1ヶ月契約' %>
                    <%= check_box_tag :payment_type,"credit_discount_month_price", false, {id: "one_month",class: "payment_type", multiple:false} %>
                </div>
                <div class="row">
                    <%= label :payment_type, '半年契約' %>
                    <%= check_box_tag :payment_type,"price_half_year",false, {id: "half_year",class: "payment_type", multiple:false} %>
                </div>
                <div class="row">
                    <%= label :payment_type, '１年契約' %>
                    <%= check_box_tag :payment_type,"price_one_year",false, {id: "one_year",class: "payment_type", multiple:false} %>
                </div>
            </div>
            <div class="col-md-2">
                <div class="terms_box">
                    <%= check_box_tag :terms, "price_one_year",false %>
                    <label id="terms-label" for="terms" style="font-size:12px;">
                        <% if current_page?(root_path) || current_page?(rental_plans_path) %>
                            <a href="https://meo.tryhatch.co.jp/kiyakumatome/meocheki" target="_blank" rel="noopener noreferrer">利用規約</a>
                        <% elsif current_page?(meo_path) %>
                            <a href="https://meo.tryhatch.co.jp/kiyakumatome/riyoukiyaku" target="_blank" rel="noopener noreferrer">利用規約</a>
                        <% elsif current_page?(hosikakutokun_path) %>
                            <a href="https://meo.tryhatch.co.jp/kiyakumatome/hoshikakutokun" target="_blank" rel="noopener noreferrer">利用規約</a>
                        <% end %>
                        に同意する</label>
                </div>
            </div>
            <div class="col-md-3">
                <div>
                    <%= submit_tag "見積書ダウンロード", {id: "download", name: "download", style: "margin-bottom:1em;",class: "btn btn-success"} %><br>
                    <%= submit_tag "申し込む", {id: "contract", name: "contract", class: "btn btn-success"} %>
                </div>
            </div>
        </div>
    </div>
</div>