config/routes.rb
Rails.application.routes.draw do

  get 'signups/new'
  get 'signups/quotation'
  get 'inquiry/new'

  root "meocheki_calc#index"

  get 'admin/index',to: 'admin#index'
  get 'rental_plans',to: 'rental_plans#index'
  get 'meo' ,to: 'meo_calc#index'
  get 'hosikakutokun',to: 'hosikakutokun_calc#index'
  get 'thanks',to: 'meocheki_calc#thanks_page'
  get 'multiple_stores', to: 'multiple_stores#index'
  
  post 'download_meocheki',to: 'download_pdf#meocheki_quotation'
  post 'download_rental',to: 'download_pdf#rental_quotation'
  post 'download_meo',to: 'download_pdf#meo_quotation'
  post 'download_hoshikakutokun',to: 'download_pdf#hoshikakutokun_quotation'

  post 'download_pdf/generate_quotation'

  resources :plans do
  end
  
  resources :inquiries 
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :signups
  post  'signups/confirm' => 'signups#confirm'   # 確認画面
  post  'signups/confirm2' => 'signups#confirm2'   # 確認画面
  post  'signups/thanks'  => 'signups#thanks'    # 送信完了画面
  post  'signups/thanks2'  => 'signups#thanks2'    # 送信完了画面


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inquiry.rb
class Inquiry
	include ActiveModel::Model
	include ActiveModel::Attributes
  attr_accessor :company_name, :department, :name, :email, 
	:phone_number, :normal, :oem, :type_of_business, :numbers_of_store, :meo_cheki, 
	:meo_support, :hoshikakutokun, :content

	attribute :company_name,  		:string, default: ''
	attribute :name,							:string, default: ''
	attribute :department, 				:string, default: ''
	attribute :email, 						:string, default: ''
	attribute :phone_number, 			:integer, default: ''
	attribute :normal, 			:boolean, default: ''
	attribute :oem, 			:boolean, default: ''
	attribute :numbers_of_store, 	:integer, default: ''
	attribute :type_of_business,	:integer, default: ''
	attribute :meo_cheki,					:boolean, default: ''
	attribute :meo_support,				:boolean, default: ''
	attribute :hoshikakutokun,		:boolean, default: ''
	attribute :content,						:integer, default: ''

  validates :company_name, :presence => {:message => '会社名の入力をお願いいたします'}
  validates :name, :presence => {:message => 'お名前の入力をお願いいたします'}
  validates :department, :presence => {:message => '部署名の入力をお願いいたします'}
  validates :email, :presence => {:message => 'Eメールアドレスの入力をお願いいたします'}
  validates :phone_number, :presence => {:message => 'お電話番号の入力をお願いいたします'}
  validates :business_type, :presence => {:message => 'お客様の事業形態の入力をお願いいたします'}
  validates :numbers_of_store, :presence => {:message => '導入予定の店舗数を入力してください'}
  validates :plans_interested, :presence => {:message => '導入をご検討されているサービスを1つ以上お選びください'}

	private
		def plans_interested
			meo_cheki.presence || meo_support.presence || hoshikakutokun.presence
		end

		def business_type
			normal.presence || oem.presence
		end

end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    @inquiry = Inquiry.new
    render :action => 'new'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:company_name, :department, 
      :name, :email, :phone_number, :type_of_business, :normal, :oem, :numbers_of_store,
      :meo_cheki, :meo_support, :hoshikakutokun, :content))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'new'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:company_name, :department, 
      :name, :email, :email, :phone_number, :type_of_business, :normal, :oem,  :numbers_of_store,
      :meo_cheki, :meo_support, :hoshikakutokun, :content))    
    InquiryMailer.inquiry_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end


end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">
	<h1>お問い合わせ内容のご確認</h1>
</div>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>会社名</th>
      <td>
        <%= f.hidden_field :company_name %>
        <%= @inquiry.company_name %>
      </td>
    </tr>
    <tr>
      <th>部署名</th>
      <td>
        <%= f.hidden_field :department %>
        <%= @inquiry.department %>
      </td>
    </tr>
    <tr>
      <th>ご担当者様</th>
      <td>
        <%= f.hidden_field :name %>
        <%= simple_format(@inquiry.name) %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= simple_format(@inquiry.email) %>
      </td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td>
        <%= f.hidden_field :phone_number %>
        <%= simple_format(@inquiry.phone_number) %>
      </td>
    </tr>
    <tr>
      <th>お客様について</th>
      <td>
        <%= f.hidden_field :type_of_business %>
        <%= simple_format(@inquiry.type_of_business) %>
      </td>
    </tr>
    <tr>
      <th>導入予定の店舗数</th>
      <td>
        <%= f.hidden_field :numbers_of_store %>
        <%= simple_format(@inquiry.numbers_of_store) %>
      </td>
    </tr>
    <tr>
      <th>MEOチェキ</th>
      <td>
        <%= f.hidden_field :meo_cheki %>
        <%= simple_format(@inquiry.meo_cheki) %>
      </td>
    </tr>
    <tr>
      <th>MEO対策コンサルティング</th>
      <td>
        <%= f.hidden_field :meo_support %>
        <%= simple_format(@inquiry.meo_support) %>
      </td>
    </tr>
    <tr>
      <th>星カクトくんα</th>
      <td>
        <%= f.hidden_field :hoshikakutokun %>
        <%= simple_format(@inquiry.hoshikakutokun) %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :content %>
        <%= simple_format(@inquiry.content) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/inquiry/new.html.erb
<div class="page-title-lv1 col-md-12">
	<span>
	<h1 style="margin-left:8rem;">CONTACT</h1>
  <p style="margin-left:8rem;">お問い合わせフォーム</p>
  <p style="margin-left:8rem;">気になることやご質問等ございましたら、ぜひ内容を記載いただき送信ください<br>
弊社営業担当から、お申し込み内容またはお問い合わせ内容についてお電話もしくはメールにて連絡させていただきます</p>
	</span>
</div>
<div class=""  style="background-color: #F5F7F8;">
			<div class="container inquiry-form">
				<div class="row">
					<div class="col-md-12 inquiry-box" >
          <div class="box">
            <div class="">
              <% if @inquiry.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <strong>入力内容にエラーがあります</strong>
                <ul>
                  <% @inquiry.errors.each do |attr, msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

          <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
            <%= f.label :会社名 %>
            <%= f.text_field :company_name, :placeholder => "会社名を入力してください" %>
            <%= f.label :部署名 %>
            <%= f.text_field :department, :placeholder => "部署名を入力してください"  %>
            <%= f.label :ご担当者様 %>
            <%= f.text_field :name, :placeholder => "お名前を入力してください"  %>
            <%= f.label :メールアドレス %>
            <%= f.text_field :email, :placeholder => "メールアドレスを入力してください"  %>
            <%= f.label :電話番号 %>
            <%= f.text_field :phone_number, :placeholder => "お電話番号を入力してください"  %>
            <label class="">お客様について</label>
            <div class="col-md-3">
            <%= f.label :自社店舗への導入を検討している %>
            <%= f.check_box :normal %>
          </div>
          <div class="col-md-3">
            <%= f.label :販売代理店・OEM販売としての導入を検討している %>
            <%= f.check_box :oem %>
          </div>
            <%= f.label :導入予定の店舗数 %>
            <%= f.text_field :numbers_of_store %>
            <br>
          <label class="">導入をご検討されているサービス</label>
          <div class="row">
          <div class="services-interested col-md-12">
          <div class="col-md-3">
            <%= f.label :MEOチェキ %>
            <%= f.check_box :meo_cheki%>
          </div>
          <div class="col-md-3">
            <%= f.label :MEO対策コンサルティング %>
            <%= f.check_box :meo_support %>
          </div>
          <div class="col-md-3">
            <%= f.label :星カクトくんα %>
            <%= f.check_box :hoshikakutokun %><br>
          </div>
          </div>
          </div>
            <%= f.label :お問い合わせ内容 %><br>
            <%= f.text_area :content %><br>
            <div class="center">
            <%= f.submit :送信する, class: 'btn btn-lg btn-primary' %><br>
            </div>
            <% end %>
                      <br>
                </div>	
            </div>
        </div>
        </div>
    </div>
		</div>
</div>
</div>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>