config/routes.rb
Rails.application.routes.draw do

  get 'signups/new'
  get 'signups/quotation'
  get 'inquiry/new'

  root "meocheki_calc#index"

  get 'admin/index',to: 'admin#index'
  get 'rental_plans',to: 'rental_plans#index'
  get 'meo' ,to: 'meo_calc#index'
  get 'hosikakutokun',to: 'hosikakutokun_calc#index'
  get 'thanks',to: 'meocheki_calc#thanks_page'
  get 'multiple_stores', to: 'multiple_stores#index'
  
  post 'download_meocheki',to: 'download_pdf#meocheki_quotation'
  post 'download_rental',to: 'download_pdf#rental_quotation'
  post 'download_meo',to: 'download_pdf#meo_quotation'
  post 'download_hoshikakutokun',to: 'download_pdf#hoshikakutokun_quotation'

  post 'download_pdf/generate_quotation'

  resources :plans do
  end
  
  resources :inquiries 
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :signups
  post  'signups/confirm' => 'signups#confirm'   # 確認画面
  post  'signups/confirm2' => 'signups#confirm2'   # 確認画面
  post  'signups/thanks'  => 'signups#thanks'    # 送信完了画面
  post  'signups/thanks2'  => 'signups#thanks2'    # 送信完了画面


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
    
    def index
        @plans=Plan.all
    end
    
    def show
    end
    
    def new
        @plan=Plan.new
    end
    
    def update
         @plan = Plan.find params[:id]
        if @plan.update(set_params)
          flash[:success] = '作成に成功しました'
          redirect_to "/plans"
        else
          flash.now[:danger] = '作成に失敗しました'
          render :new
        end
    end
    
    def create
        @plan = set_params
        if Plan.create(@plan)
          flash[:success] = '作成に成功しました'
          redirect_to "/plans"
        else
          flash.now[:danger] = '作成に失敗しました'
          render :new
        end
    end
    
    def edit
        @plan = Plan.find params[:id]
    end
    
    def destroy
        @plan = Plan.find params[:id]
        if @plan.destroy
          flash[:success] = '削除しました'
        else
          flash[:danger] = '削除できませんでした'
        end
        redirect_to plans_path
    end
    
    private
    
    def set_params
        params[:plan].permit(
            :name,
            :max_keywords,
            :business_limit,
            :init_price,
            :month_price,
            :credit_discount_init_price,
            :credit_discount_month_price,
            :price_half_year,
            :price_one_year,
            :time_crawler_limit,
            :time_crawler_price,
            :base_location_limit,
            :base_location_price,
            :business_restricted,
            :calendar_restricted,
            :chart_restricted,
            :insight_restricted,
            :export_csv_restricted,
            :post_restricted,
            :memo_restricted,
            :auto_post_restricted,
            :reviews_restricted,
            :auto_reply_reviews_restricted,
            :hoshikakutokun_restricted,
            :service_id
            )
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
 <%= form_for @plan do |f| %>
    <div class="form-group">
      <label>プラン名</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :max_keywords, "最大キーワード数" %>
      <%= f.number_field :max_keywords, id: :max_keywords_basic_form, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :business_limit, "最大案件数" %>
      <%= f.number_field :business_limit, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>初期費用（円）</label>
      <%= f.number_field :init_price, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>月額費用（円）</label>
      <%= f.number_field :month_price, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>初期費用(クレカ割引後)（円）</label>
      <%= f.number_field :credit_discount_init_price, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>月額費用(クレカ割引後)（円）</label>
      <%= f.number_field :credit_discount_month_price, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>6ヶ月額費用(クレカ割引後)（円）</label>
      <%= f.number_field :price_half_year, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>12ヶ月額費用(クレカ割引後)（円）</label>
      <%= f.number_field :price_one_year, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :time_crawler_limit, "検索時間数" %>
      <%= f.number_field :time_crawler_limit, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :time_crawler_price, "検索時間単価（円）" %>
      <%= f.number_field :time_crawler_price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :base_location_limit, "検索住所数" %>
      <%= f.number_field :base_location_limit, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :base_location_price, "検索住所単価（円）" %>
      <%= f.number_field :base_location_price, class: "form-control" %>
    </div>
   
    <div class="form-group">
      <%= f.check_box :business_restricted, {}, false, true %>
      <label>案件機能</label>
    </div>
    <div class="form-group">
      <%= f.check_box :calendar_restricted, {}, false, true %>
      <label>カレンダー</label>
    </div>
    <div class="form-group">
      <%= f.check_box :chart_restricted, {}, false, true %>
      <label>順位チャート</label>
    </div>
    <div class="form-group">
      <%= f.check_box :insight_restricted, {}, false, true %>
      <label>インサイト</label>
    </div>
    <div class="form-group">
      <%= f.check_box :export_csv_restricted, {}, false, true %>
      <label>CSV出力</label>
    </div>
    <div class="form-group">
      <%= f.check_box :post_restricted, {}, false, true %>
      <label>投稿機能</label>
    </div>
    <div class="form-group">
      <%= f.check_box :memo_restricted, {}, false, true %>
      <label>メモ機能</label>
    </div>
    <div class="form-group">
      <%= f.check_box :auto_post_restricted, {}, false, true %>
      <label>投稿予約機能</label>
    </div>
    <div class="form-group">
      <%= f.check_box :reviews_restricted, {}, false, true %>
      <label>レビュー分析</label>
    </div>
    <div class="form-group">
      <%= f.check_box :auto_reply_reviews_restricted, {}, false, true %>
      <label>口コミ自動返信機能</label>
    </div>
    <div class="form-group">
      <%= f.check_box :hoshikakutokun_restricted, {}, false, true %>
      <label>星カクトくん</label>
    </div>
    <div class="form-group">
      <label>対象媒体</label>
      <small>
        ※ 順位取得の対象となる媒体
      </small>
      <%#= f.select :provider_type, options_for_select(Plan.provider_type.keys.map{|k| [t("plans.provider_type.#{k.to_s}"), k]},
        selected: @plan.provider_type || Plan.provider_types.first), {include_blank: false}, class: "form-control" %>
    </div>
    <div class="form-group">
    <%=  f.select :service_id, [['MEOチェキ', "meocheki"], ['レンタルプラン', "rental"],['MEO対策', "meo"],['星カクトくん', "hosikakutokun"]], {selected: "meocheki"}, {} %>
    </div>
    
    <div class="pull-right">
        <%= link_to 'キャンセル', plans_path, class: 'btn btn-default' %>
        <%= f.submit '保存', class: 'btn btn-success plan_submit' %>
    </div>
<% end %>

app/views/plans/edit.html.erb
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box" style="margin-left:10em">
        <div class="box-header">
          <h3 class="box-title">プラン編集</h3>
        </div>
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/plans/index.html.erb
<% @plans.each do |plan| %>
<section class="content">
    <div class="container border shadow col-md-8 col-xs-12" style="margin-left:10em;padding:2em;">
        <h4><%= plan.name %></h4>
        <div class="row">
            <div class="col-md-3 col-xs-6">
                month_price：<%= plan.month_price %><br>
                price_half_year：<%= plan.price_half_year %><br>
                price_one_year：<%= plan.price_one_year %><br>
                init_price：<%= plan.init_price %><br>
                credit_discount_month_price：<%= plan.credit_discount_month_price %><br>
                credit_discount_init_price：<%= plan.credit_discount_init_price %><br>
                calendar_restricted：<%= plan.calendar_restricted %><br>
                chart_restricted：<%= plan.chart_restricted %><br>
                insight_restricted：<%= plan.insight_restricted %><br>
                export_csv_restricted：<%= plan.export_csv_restricted %><br>
                post_restricted：<%= plan.post_restricted %><br>
            </div>
            <div class="col-md-3 col-xs-6">
                auto_post_restricted：<%= plan.auto_post_restricted %><br>
                memo_restricted：<%= plan.memo_restricted %><br>
                reviews_restricted：<%= plan.reviews_restricted %><br>
                auto_reply_reviews_restricted：<%= plan.auto_reply_reviews_restricted %><br>
                business_restricted：：<%= plan.business_restricted %><br>
                hoshikakutokun_restricted：<%= plan.hoshikakutokun_restricted %><br>
                provider_type：<%= plan.provider_type %><br>
                max_keywords：<%= plan.max_keywords %><br>
                max_sms_by_month：<%= plan.max_sms_by_month %><br>
                business_limit：<%= plan.business_limit %><br>
                time_crawler_limit：<%= plan.time_crawler_limit %><br>
                time_crawler_price：<%= plan.time_crawler_price %><br>
                base_location_limit：<%= plan.base_location_limit %><br>
                base_location_price：<%= plan.base_location_price %><br>
                <%= link_to edit_plan_path(plan), class: "btn btn-success" do %>
                  <i class="fa fa-pencil"></i>
                <% end %>
                <%= link_to plan_path(plan), method: :delete, class: "btn btn-success" do %>
                  <i class="fa fa-trash"></i>
                <% end %>
            </div>
        </div>
    </div>
    </section>
    <br>
<% end %>

app/views/plans/new.html.erb
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box" style="margin-left:10em">
        <div class="box-header">
          <h3 class="box-title">プラン作成</h3>
        </div>
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>